import { Roboto } from 'next/font/google'

import "./globals.css";
import Provider from "./Provider";

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
            {children}
        </Provider>
        </body>
    </html>
  );
}
